import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer"; 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "recipe-application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) { 
 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main className="container mx-auto px-4 mt-[100px]">

        {children}

        </main>
        <Footer />
      </body>
    </html>
  );
}
